### ISSUE TITLE
python3 running for a longtime and Takes up a lot of memory

### ISSUE THREAD

**Issue by biozhangzhou** [yanboANU/Kmer2SNP#1]
hello!
Everything is ok before #python3 kmerGraphCalling.py ;then python running for 2 days and takes up 1.1T memory. 
Please let me know how would it happen??

**Comment by yanboANU** [comment]
Could do provide some details? for example genome size,  heterozygous rate and the log file of running kmerGraphCalling.py?

**Comment by biozhangzhou** [comment]
############################
Start at
Mon May 25 15:53:41 CST 2020
$1:kmer-size $2:homo coverage $3:input.fq
31 50 ERR2984475_fastq.gz
Error in library("fGarch") : there is no package called ‘fGarch’
Calls: findGSE
Execution halted
Start at
Mon May 25 15:59:10 CST 2020
$1:kmer-size $2:homo coverage $3:input.fq
31 50 ERR2984475_fastq.gz
Warning message:
In dir.create(file.path(path), showWarnings = T) : '.' already exists
3
9
python3 ~/1.bin/Kmer2SNP/Kmer2SNP/kmerGraphCalling.py --t1 chr_k31.txt --c1 3 --c2 9 --k 31 >vc_k31.log
INFO:root:heterozygous kmer coverage range 2 10
INFO:root:picked heterozygous Kmer number: 1823047277
../runkmercalling.sh: line 42: 213406 Terminated              ~/1.bin/miniconda2/envs/py36/bin/python3 
~/1.bin/Kmer2SNP/Kmer2SNP/kmerGraphCalling.py --t1 chr_k$1.txt --c1 $left --c2 $right --k $1 > vc_k$1.log
#######################
Thank you! This is the log file above. Moreover, The genome size I'm using is 2.5G , not clear about the heterozygous rate but should not over 10% .

**Comment by yanboANU** [comment]
It seems your findGSE already wrong.

"Error in library("fGarch") : there is no package called ‘fGarch’
Calls: findGSE
Execution halted"

The coverage range (3, 9) is not correct Given $2:homo coverage = 50.


-----------------------------------------------
Yanbo Li
4.32, Building 145 (Hanna Neumann)
Research School of Computer Science
The Australian National University

Email: yanbo.li@anu.edu.au<mailto:yu.lin@anu.edu.au>


________________________________

**Comment by biozhangzhou** [comment]
First: I fixed the "Error in library("fGarch") : there is no package called ‘fGarch’ and Start again,see the other  "Start at";
second: the coverage may not be 50 ,cause my PE .gz data only 15G each, It's about 60G total ?? Then the coverage should be ~30,should i change this parament?

**Comment by yanboANU** [comment]
If your coverage is ~30, you should set the parameter 30. You can look at *.curvefitted.pdf generated by findGSE to further check your coverage.

**Comment by biozhangzhou** [comment]
hello,I have one more qusetion. 
As you paper mentioned , Kmer2SNP should be very fast, but i 
think i stuck in step "Kmer2SNP/kmerGraphCalling.py --t1 chr_k31.txt --c1 3 --c2 12 --k 31"  by follow your simple 
standard command，should i change some args to make python more efficient? 

PS：I'm handle with 30G fasta reads in a powerful Server, but python step uses 1 cpu and running exceeding 12h.

**Comment by yanboANU** [comment]
--c1 3 is too small. In this way, you cannot filter error k-mer. You should know the coverage of your dataset. --c1 --c2 should around haplotype coverage.


For example,  sh runkmercalling.sh 31 60 single_chr22_60x_data.fq,
60 is input coverage (which is reads coverage or homozygous coverage ). --c1 --c2 should around 30, like c1 ==15 and c2=35.




-----------------------------------------------
Yanbo Li
4.32, Building 145 (Hanna Neumann)
Research School of Computer Science
The Australian National University

Email: yanbo.li@anu.edu.au<mailto:yu.lin@anu.edu.au>


________________________________

**Comment by yanboANU** [comment]
> hello,I have one more qusetion.
> As you paper mentioned , Kmer2SNP should be very fast, but i
> think i stuck in step "Kmer2SNP/kmerGraphCalling.py --t1 chr_k31.txt --c1 3 --c2 12 --k 31" by follow your simple
> standard command，should i change some args to make python more efficient?
> 
> PS：I'm handle with 30G fasta reads in a powerful Server, but python step uses 1 cpu and running exceeding 12h.

Our algorithm does not suit for dataset with low coverage (homozygous coverage smaller than 40x).
