### ISSUE TITLE
How to run with PE reads?

### ISSUE THREAD

**Issue by ghost** [yanboANU/Kmer2SNP#2]
Hello,

how should it be run with PE reads?
thanks

**Comment by yanboANU** [comment]
Hi,

If there are more than 2 input fastq file, 

sh runkmercalling.sh 31 60 single_chr22_60x_p1_data.fq,single_chr22_60x_p2_data.fq

**Comment by ghost** [comment]
thanks,

would it actually make sense to juste use the R1 reads? As often the R2 reads in illumina sequencing are of lower quality

**Comment by yanboANU** [comment]
If your coverage is enough, just use R1 reads is ok I think. I never heard that R2 reads in illumina are of lower quality.



在 2020年7月30日，下午7:37，aderzelle <notifications@github.com> 写道：

﻿

thanks,

would it actually make sense to juste use the R1 reads? Are often the R2 reads in illumina sequencing are of lower quality

**Comment by ghost** [comment]
Oh for example: 
![Quality-profiles-for-R1-and-R2-reads-the-boxplots-in-the-first-column-display-the](https://user-images.githubusercontent.com/23341393/88954010-0510b900-d29a-11ea-8c99-5382bd42e14c.png)

This comes from: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4381044/

So Kmer2SNP does not use paired information right? It is indifferent if the reads are paired or not for it to run?

**Comment by yanboANU** [comment]
Yes, Kmer2SNP does not use paired information.

-----------------------------------------------
Yanbo Li
4.32, Building 145 (Hanna Neumann)
Research School of Computer Science
The Australian National University

Email: yanbo.li@anu.edu.au<mailto:yu.lin@anu.edu.au>


________________________________

**Comment by ghost** [comment]
cool thanks
