### ISSUE TITLE
connected_component_subgraphs is removed in NetworkX 2.4

### ISSUE THREAD

**Issue by tbenavi1** [yanboANU/Kmer2SNP#4]
Hello,

On line 53 of kmerGraphCalling.py, you use the deprecated function connected_component_subgraphs. I believe that the current way to get this information is now G.subgraph(c) for c in nx.connected_components(G). Would it be possible to update this in your code? Thank you.

**Comment by yanboANU** [comment]
I have updated this in my code. Thanks.
