### ISSUE TITLE
Empty hete.peak.k$1 file created if Rscript line fails

### ISSUE THREAD

**Issue by tbenavi1** [yanboANU/Kmer2SNP#6]
Hello,

On line 24 of runkmercalling.sh, the code will create an empty hete.peak.k$1 file if Rscript is unable to properly run. This causes issues when trying to rerun Kmer2SNP after fixing the Rscript issue. Would it be possible to make Kmer2SNP not produce a file if there is an error. For example, perhaps changing the line to:

out=$(Rscript /path2Kmer2SNP/Kmer2SNP/libprism/local/runfindGSE.r chr_k$1.histo $1 ./ $2) && echo "$out" > hete.peak.k$1

according to https://stackoverflow.com/questions/31424456/how-to-redirect-output-of-a-program-only-if-it-succeeded. Thanks.

**Comment by yanboANU** [comment]
Thanks for you advice, I will update my code soon.

-----------------------------------------------
Yanbo Li
4.32, Building 145 (Hanna Neumann)
Research School of Computer Science
The Australian National University

Email: yanbo.li@anu.edu.au<mailto:yu.lin@anu.edu.au>


________________________________
