### ISSUE TITLE
Error in findGSE

### ISSUE THREAD

**Issue by stefanerb89** [yanboANU/Kmer2SNP#7]
Hello, 

my command is "sh $path_to_kmer2snp 31 30 1.fastq,2.fastq,3.fastq

I get the following error even when I change the parameters k and coverage:

```
Error in findGSE(histo = args[1], sizek = args[2], outdir = args[3], exp_hom = strtoi(args[4])) : 
  No k-mer freq peak was found with the cutoff given by -exp_hom.
                  You may need to increase the cutoff!
```
What I am doing wrong?

**Comment by yanboANU** [comment]
You may give the wrong coverage. findGSE estimates heterozygous peak and homozygous peak according to the coverage you given.


________________________________

**Comment by stefanerb89** [comment]
Thank you for your comment! It is exome capture data. Maybe it's because only exons have high coverage (30x). Average coverage is only 1.4 ?
